# Generated by Django 5.1.7 on 2025-04-13 00:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Taxi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('driver_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('car_type', models.CharField(max_length=100)),
                ('capacity', models.PositiveIntegerField()),
                ('pickup_location', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('one_way_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('return_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('journey_date', models.DateField()),
                ('return_date', models.DateField(blank=True, null=True)),
                ('passengers', models.PositiveIntegerField(default=1)),
                ('flight_type', models.CharField(choices=[('oneway', 'One Way'), ('return', 'Return')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('taxi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transfer.taxi')),
            ],
        ),
    ]
